[project]
name = "event-sourcing-d"
version = "0.1.0"
description = "Executable cli application to demonstrate event sourced application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eventsourcing>=9.4.6",
    "typer>=0.20.0",
]
